# Generated by Django 5.0.1 on 2024-01-23 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        ("borrowing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="borrowing date can't be earlier than expected return date",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="borrowing date can't be earlier than actual return date",
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expected_return_date__gt", models.F("borrowing_date"))
                ),
                name="borrowing date can't be earlier than expected return date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(("actual_return_date__gte", models.F("borrowing_date"))),
                name="borrowing date can't be earlier than actual return date",
            ),
        ),
    ]
