# Generated by Django 4.2.8 on 2024-01-26 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "borrowing",
            "0002_remove_borrowing_borrowing_date_can_t_be_earlier_than_expected_return_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("borrowing_date",)},
        ),
    ]
