# Generated by Django 4.2.8 on 2024-01-26 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0003_alter_borrowing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("id",)},
        ),
    ]
